/*
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.ui.tests;

import ca.mcgill.devops.pipeline.ui.internal.PipelineActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PipelineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PipelineActivator.getInstance().getInjector("ca.mcgill.devops.pipeline.Pipeline");
	}

}
