/*
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.ide.contentassist.antlr;

import ca.mcgill.devops.pipeline.ide.contentassist.antlr.internal.InternalPipelineParser;
import ca.mcgill.devops.pipeline.services.PipelineGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PipelineParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PipelineGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PipelineGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getPipelineAccess().getAlternatives_4_1(), "rule__Pipeline__Alternatives_4_1");
			builder.put(grammarAccess.getPipelineAccess().getGroupAlternatives_5_1_1_1_0(), "rule__Pipeline__GroupAlternatives_5_1_1_1_0");
			builder.put(grammarAccess.getPipelineAccess().getCancelConcurrenceAlternatives_5_1_2_1_0(), "rule__Pipeline__CancelConcurrenceAlternatives_5_1_2_1_0");
			builder.put(grammarAccess.getPipelineAccess().getVmImageAlternatives_7_1_0_2_1_0(), "rule__Pipeline__VmImageAlternatives_7_1_0_2_1_0");
			builder.put(grammarAccess.getPipelineAccess().getVmDemandsAlternatives_7_1_1_0_1_0(), "rule__Pipeline__VmDemandsAlternatives_7_1_1_0_1_0");
			builder.put(grammarAccess.getPipelineAccess().getJobOrStageVarAlternatives_12_1_0_0(), "rule__Pipeline__JobOrStageVarAlternatives_12_1_0_0");
			builder.put(grammarAccess.getPipelineAccess().getAlternatives_12_1_2(), "rule__Pipeline__Alternatives_12_1_2");
			builder.put(grammarAccess.getExtendedParameterAccess().getAlternatives(), "rule__ExtendedParameter__Alternatives");
			builder.put(grammarAccess.getVariableAccess().getAlternatives(), "rule__Variable__Alternatives");
			builder.put(grammarAccess.getResourceAccess().getResourceNameAlternatives_0_0(), "rule__Resource__ResourceNameAlternatives_0_0");
			builder.put(grammarAccess.getResourceAccess().getAlternatives_1(), "rule__Resource__Alternatives_1");
			builder.put(grammarAccess.getPipelineParameterAccess().getAlternatives(), "rule__PipelineParameter__Alternatives");
			builder.put(grammarAccess.getPipelineParameterAccess().getNameAlternatives_1_0_0(), "rule__PipelineParameter__NameAlternatives_1_0_0");
			builder.put(grammarAccess.getEventAccess().getAlternatives(), "rule__Event__Alternatives");
			builder.put(grammarAccess.getEventAccess().getAlternatives_0_2_1(), "rule__Event__Alternatives_0_2_1");
			builder.put(grammarAccess.getEventAccess().getAlternatives_0_2_2_3_1(), "rule__Event__Alternatives_0_2_2_3_1");
			builder.put(grammarAccess.getEventAccess().getAlternatives_0_2_2_3_1_0(), "rule__Event__Alternatives_0_2_2_3_1_0");
			builder.put(grammarAccess.getEventAccess().getAlternatives_0_2_2_4_1(), "rule__Event__Alternatives_0_2_2_4_1");
			builder.put(grammarAccess.getEventAccess().getAlternatives_0_2_2_4_1_0(), "rule__Event__Alternatives_0_2_2_4_1_0");
			builder.put(grammarAccess.getEventAccess().getAlternatives_1(), "rule__Event__Alternatives_1");
			builder.put(grammarAccess.getEventAccess().getNameAlternatives_1_0_0_0(), "rule__Event__NameAlternatives_1_0_0_0");
			builder.put(grammarAccess.getEventAccess().getNameAlternatives_1_1_0_0(), "rule__Event__NameAlternatives_1_1_0_0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getAlternatives_0(), "rule__TriggerSchedule__Alternatives_0");
			builder.put(grammarAccess.getBranchAccess().getNameAlternatives_1_0(), "rule__Branch__NameAlternatives_1_0");
			builder.put(grammarAccess.getActivityAccess().getNameAlternatives_0(), "rule__Activity__NameAlternatives_0");
			builder.put(grammarAccess.getStageAccess().getAlternatives_1_1_1(), "rule__Stage__Alternatives_1_1_1");
			builder.put(grammarAccess.getStageAccess().getVmImageAlternatives_1_1_1_1_0_2_1_0(), "rule__Stage__VmImageAlternatives_1_1_1_1_0_2_1_0");
			builder.put(grammarAccess.getStageAccess().getVmDemandsAlternatives_1_1_1_1_1_0_1_0(), "rule__Stage__VmDemandsAlternatives_1_1_1_1_1_0_1_0");
			builder.put(grammarAccess.getJobAccess().getAlternatives_0_0_1(), "rule__Job__Alternatives_0_0_1");
			builder.put(grammarAccess.getJobAccess().getNameAlternatives_0_1_0(), "rule__Job__NameAlternatives_0_1_0");
			builder.put(grammarAccess.getJobAccess().getNameKWAlternatives_1_0_1_0_0(), "rule__Job__NameKWAlternatives_1_0_1_0_0");
			builder.put(grammarAccess.getJobAccess().getDependKWAlternatives_1_1_0_0(), "rule__Job__DependKWAlternatives_1_1_0_0");
			builder.put(grammarAccess.getJobAccess().getAlternatives_1_1_1(), "rule__Job__Alternatives_1_1_1");
			builder.put(grammarAccess.getJobParameterAccess().getAlternatives_0(), "rule__JobParameter__Alternatives_0");
			builder.put(grammarAccess.getJobParameterAccess().getAlternatives_1(), "rule__JobParameter__Alternatives_1");
			builder.put(grammarAccess.getJobParameterAccess().getValueAlternatives_1_0_0(), "rule__JobParameter__ValueAlternatives_1_0_0");
			builder.put(grammarAccess.getStepAccess().getAlternatives_1(), "rule__Step__Alternatives_1");
			builder.put(grammarAccess.getScriptAccess().getNameAlternatives_0_0_0(), "rule__Script__NameAlternatives_0_0_0");
			builder.put(grammarAccess.getScriptAccess().getAlternatives_0_1(), "rule__Script__Alternatives_0_1");
			builder.put(grammarAccess.getScriptAccess().getAlternatives_0_1_1_0(), "rule__Script__Alternatives_0_1_1_0");
			builder.put(grammarAccess.getScriptAccess().getSubStepsAlternatives_1_1_0(), "rule__Script__SubStepsAlternatives_1_1_0");
			builder.put(grammarAccess.getActionAccess().getAlternatives_0(), "rule__Action__Alternatives_0");
			builder.put(grammarAccess.getActionAccess().getAlternatives_0_1_0(), "rule__Action__Alternatives_0_1_0");
			builder.put(grammarAccess.getActionAccess().getSubStepsAlternatives_1_1_0(), "rule__Action__SubStepsAlternatives_1_1_0");
			builder.put(grammarAccess.getParameterValueAccess().getNameAlternatives_1_0(), "rule__ParameterValue__NameAlternatives_1_0");
			builder.put(grammarAccess.getParameterValueAccess().getAlternatives_4(), "rule__ParameterValue__Alternatives_4");
			builder.put(grammarAccess.getParameterValueAccess().getValueAlternatives_4_1_0_0(), "rule__ParameterValue__ValueAlternatives_4_1_0_0");
			builder.put(grammarAccess.getAnyDataAccess().getAlternatives(), "rule__AnyData__Alternatives");
			builder.put(grammarAccess.getIndPermissionValueAccess().getAlternatives_2(), "rule__IndPermissionValue__Alternatives_2");
			builder.put(grammarAccess.getUnquotedStringAccess().getAlternatives_1(), "rule__UnquotedString__Alternatives_1");
			builder.put(grammarAccess.getHyphenValuesAccess().getAlternatives(), "rule__HyphenValues__Alternatives");
			builder.put(grammarAccess.getPipelineKeywordAccess().getAlternatives(), "rule__PipelineKeyword__Alternatives");
			builder.put(grammarAccess.getPipelineAccess().getGroup_0(), "rule__Pipeline__Group_0__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_1(), "rule__Pipeline__Group_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_2_0(), "rule__Pipeline__Group_2_0__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_2_0_4(), "rule__Pipeline__Group_2_0_4__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_2_1(), "rule__Pipeline__Group_2_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_2_1_0(), "rule__Pipeline__Group_2_1_0__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_3(), "rule__Pipeline__Group_3__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_3_2(), "rule__Pipeline__Group_3_2__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_4(), "rule__Pipeline__Group_4__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_4_1_1(), "rule__Pipeline__Group_4_1_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_5(), "rule__Pipeline__Group_5__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_5_1(), "rule__Pipeline__Group_5_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_5_1_1(), "rule__Pipeline__Group_5_1_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_5_1_2(), "rule__Pipeline__Group_5_1_2__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_7(), "rule__Pipeline__Group_7__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_7_1_0(), "rule__Pipeline__Group_7_1_0__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_7_1_0_1(), "rule__Pipeline__Group_7_1_0_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_7_1_0_2(), "rule__Pipeline__Group_7_1_0_2__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_7_1_1(), "rule__Pipeline__Group_7_1_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_7_1_1_0(), "rule__Pipeline__Group_7_1_1_0__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_8(), "rule__Pipeline__Group_8__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_8_1(), "rule__Pipeline__Group_8_1__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_9(), "rule__Pipeline__Group_9__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_10(), "rule__Pipeline__Group_10__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_12(), "rule__Pipeline__Group_12__0");
			builder.put(grammarAccess.getPipelineAccess().getGroup_12_1(), "rule__Pipeline__Group_12_1__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_0(), "rule__ExtendedParameter__Group_0__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_0_1(), "rule__ExtendedParameter__Group_0_1__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_0_1_1(), "rule__ExtendedParameter__Group_0_1_1__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_0_1_2(), "rule__ExtendedParameter__Group_0_1_2__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_0_1_2_1(), "rule__ExtendedParameter__Group_0_1_2_1__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_1(), "rule__ExtendedParameter__Group_1__0");
			builder.put(grammarAccess.getExtendedParameterAccess().getGroup_1_1(), "rule__ExtendedParameter__Group_1_1__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_0(), "rule__Variable__Group_0__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1(), "rule__Variable__Group_1__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1_0(), "rule__Variable__Group_1_0__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1_1(), "rule__Variable__Group_1_1__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1_1_0(), "rule__Variable__Group_1_1_0__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1_1_1(), "rule__Variable__Group_1_1_1__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1_1_1_1(), "rule__Variable__Group_1_1_1_1__0");
			builder.put(grammarAccess.getVariableAccess().getGroup_1_1_1_2(), "rule__Variable__Group_1_1_1_2__0");
			builder.put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
			builder.put(grammarAccess.getResourceAccess().getGroup_1_0(), "rule__Resource__Group_1_0__0");
			builder.put(grammarAccess.getResourceAccess().getGroup_1_1(), "rule__Resource__Group_1_1__0");
			builder.put(grammarAccess.getResourceAccess().getGroup_1_1_1(), "rule__Resource__Group_1_1_1__0");
			builder.put(grammarAccess.getPipelineParameterAccess().getGroup_0(), "rule__PipelineParameter__Group_0__0");
			builder.put(grammarAccess.getPipelineParameterAccess().getGroup_1(), "rule__PipelineParameter__Group_1__0");
			builder.put(grammarAccess.getPipelineParameterAccess().getGroup_1_1(), "rule__PipelineParameter__Group_1_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0(), "rule__Event__Group_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_0(), "rule__Event__Group_0_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2(), "rule__Event__Group_0_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_1_0(), "rule__Event__Group_0_2_1_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_1_1(), "rule__Event__Group_0_2_1_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_0(), "rule__Event__Group_0_2_2_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_1(), "rule__Event__Group_0_2_2_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_2(), "rule__Event__Group_0_2_2_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_3(), "rule__Event__Group_0_2_2_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_3_1_0_1(), "rule__Event__Group_0_2_2_3_1_0_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_3_1_0_1_2(), "rule__Event__Group_0_2_2_3_1_0_1_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_3_1_1(), "rule__Event__Group_0_2_2_3_1_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_3_1_1_2(), "rule__Event__Group_0_2_2_3_1_1_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_3_1_1_3(), "rule__Event__Group_0_2_2_3_1_1_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_4(), "rule__Event__Group_0_2_2_4__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_4_1_0_1(), "rule__Event__Group_0_2_2_4_1_0_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_4_1_0_1_2(), "rule__Event__Group_0_2_2_4_1_0_1_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_4_1_1(), "rule__Event__Group_0_2_2_4_1_1__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_5(), "rule__Event__Group_0_2_2_5__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_5_2(), "rule__Event__Group_0_2_2_5_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_5_2_2(), "rule__Event__Group_0_2_2_5_2_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_5_2_3(), "rule__Event__Group_0_2_2_5_2_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_6(), "rule__Event__Group_0_2_2_6__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_6_2(), "rule__Event__Group_0_2_2_6_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_7(), "rule__Event__Group_0_2_2_7__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_7_2(), "rule__Event__Group_0_2_2_7_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_7_2_2(), "rule__Event__Group_0_2_2_7_2_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_7_2_3(), "rule__Event__Group_0_2_2_7_2_3__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_8(), "rule__Event__Group_0_2_2_8__0");
			builder.put(grammarAccess.getEventAccess().getGroup_0_2_2_8_2(), "rule__Event__Group_0_2_2_8_2__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1_0(), "rule__Event__Group_1_0__0");
			builder.put(grammarAccess.getEventAccess().getGroup_1_1(), "rule__Event__Group_1_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup(), "rule__TriggerSchedule__Group__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_0_0(), "rule__TriggerSchedule__Group_0_0__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_0_1(), "rule__TriggerSchedule__Group_0_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_0_1_1(), "rule__TriggerSchedule__Group_0_1_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1(), "rule__TriggerSchedule__Group_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_1(), "rule__TriggerSchedule__Group_1_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_2(), "rule__TriggerSchedule__Group_1_2__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_2_1(), "rule__TriggerSchedule__Group_1_2_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_2_1_1(), "rule__TriggerSchedule__Group_1_2_1_1__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_2_1_2(), "rule__TriggerSchedule__Group_1_2_1_2__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_3_0(), "rule__TriggerSchedule__Group_1_3_0__0");
			builder.put(grammarAccess.getTriggerScheduleAccess().getGroup_1_3_1(), "rule__TriggerSchedule__Group_1_3_1__0");
			builder.put(grammarAccess.getBranchAccess().getGroup(), "rule__Branch__Group__0");
			builder.put(grammarAccess.getStageAccess().getGroup(), "rule__Stage__Group__0");
			builder.put(grammarAccess.getStageAccess().getGroup_0(), "rule__Stage__Group_0__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_0(), "rule__Stage__Group_1_0__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_0_1(), "rule__Stage__Group_1_0_1__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_1(), "rule__Stage__Group_1_1__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_1_1_1_0(), "rule__Stage__Group_1_1_1_1_0__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_1_1_1_0_1(), "rule__Stage__Group_1_1_1_1_0_1__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_1_1_1_0_2(), "rule__Stage__Group_1_1_1_1_0_2__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_1_1_1_1(), "rule__Stage__Group_1_1_1_1_1__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_1_1_1_1_0(), "rule__Stage__Group_1_1_1_1_1_0__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_2(), "rule__Stage__Group_1_2__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_3(), "rule__Stage__Group_1_3__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_4(), "rule__Stage__Group_1_4__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_5(), "rule__Stage__Group_1_5__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_6(), "rule__Stage__Group_1_6__0");
			builder.put(grammarAccess.getStageAccess().getGroup_1_6_0(), "rule__Stage__Group_1_6_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup(), "rule__Job__Group__0");
			builder.put(grammarAccess.getJobAccess().getGroup_0(), "rule__Job__Group_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_0_0(), "rule__Job__Group_0_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_0(), "rule__Job__Group_1_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_0_1(), "rule__Job__Group_1_0_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_1(), "rule__Job__Group_1_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_1_1_1(), "rule__Job__Group_1_1_1_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_1_1_1_2(), "rule__Job__Group_1_1_1_1_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_2(), "rule__Job__Group_1_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_1_2_1(), "rule__Job__Group_1_2_1__0");
			builder.put(grammarAccess.getJobParameterAccess().getGroup(), "rule__JobParameter__Group__0");
			builder.put(grammarAccess.getJobParameterAccess().getGroup_0_1(), "rule__JobParameter__Group_0_1__0");
			builder.put(grammarAccess.getJobParameterAccess().getGroup_1_1(), "rule__JobParameter__Group_1_1__0");
			builder.put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
			builder.put(grammarAccess.getScriptAccess().getGroup(), "rule__Script__Group__0");
			builder.put(grammarAccess.getScriptAccess().getGroup_0(), "rule__Script__Group_0__0");
			builder.put(grammarAccess.getScriptAccess().getGroup_0_1_1(), "rule__Script__Group_0_1_1__0");
			builder.put(grammarAccess.getScriptAccess().getGroup_1(), "rule__Script__Group_1__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_0_0(), "rule__Action__Group_0_0__0");
			builder.put(grammarAccess.getActionAccess().getGroup_0_1(), "rule__Action__Group_0_1__0");
			builder.put(grammarAccess.getActionAccess().getGroup_0_1_0_1(), "rule__Action__Group_0_1_0_1__0");
			builder.put(grammarAccess.getActionAccess().getGroup_1(), "rule__Action__Group_1__0");
			builder.put(grammarAccess.getParameterValueAccess().getGroup(), "rule__ParameterValue__Group__0");
			builder.put(grammarAccess.getParameterValueAccess().getGroup_4_0(), "rule__ParameterValue__Group_4_0__0");
			builder.put(grammarAccess.getParameterValueAccess().getGroup_4_1(), "rule__ParameterValue__Group_4_1__0");
			builder.put(grammarAccess.getParameterValueAccess().getGroup_4_1_1(), "rule__ParameterValue__Group_4_1_1__0");
			builder.put(grammarAccess.getKeyValueAccess().getGroup(), "rule__KeyValue__Group__0");
			builder.put(grammarAccess.getIndPermissionValueAccess().getGroup(), "rule__IndPermissionValue__Group__0");
			builder.put(grammarAccess.getUnquotedStringAccess().getGroup(), "rule__UnquotedString__Group__0");
			builder.put(grammarAccess.getHyphenValuesAccess().getGroup_0(), "rule__HyphenValues__Group_0__0");
			builder.put(grammarAccess.getHyphenValuesAccess().getGroup_1(), "rule__HyphenValues__Group_1__0");
			builder.put(grammarAccess.getHyphenValuesAccess().getGroup_1_1(), "rule__HyphenValues__Group_1_1__0");
			builder.put(grammarAccess.getArrayListAccess().getGroup(), "rule__ArrayList__Group__0");
			builder.put(grammarAccess.getArrayListAccess().getGroup_1(), "rule__ArrayList__Group_1__0");
			builder.put(grammarAccess.getArrayListAccess().getGroup_1_1(), "rule__ArrayList__Group_1_1__0");
			builder.put(grammarAccess.getPipelineAccess().getNameAssignment_0_1(), "rule__Pipeline__NameAssignment_0_1");
			builder.put(grammarAccess.getPipelineAccess().getRunNameAssignment_1_1(), "rule__Pipeline__RunNameAssignment_1_1");
			builder.put(grammarAccess.getPipelineAccess().getDefaultShellValueAssignment_2_0_4_1(), "rule__Pipeline__DefaultShellValueAssignment_2_0_4_1");
			builder.put(grammarAccess.getPipelineAccess().getDefaultWDValueAssignment_2_1_0_1(), "rule__Pipeline__DefaultWDValueAssignment_2_1_0_1");
			builder.put(grammarAccess.getPipelineAccess().getEnvAssignment_3_2_1(), "rule__Pipeline__EnvAssignment_3_2_1");
			builder.put(grammarAccess.getPipelineAccess().getAllPermissionAssignment_4_1_0(), "rule__Pipeline__AllPermissionAssignment_4_1_0");
			builder.put(grammarAccess.getPipelineAccess().getIndPermissionsAssignment_4_1_1_1(), "rule__Pipeline__IndPermissionsAssignment_4_1_1_1");
			builder.put(grammarAccess.getPipelineAccess().getGroupAssignment_5_1_1_1(), "rule__Pipeline__GroupAssignment_5_1_1_1");
			builder.put(grammarAccess.getPipelineAccess().getCancelConcurrenceAssignment_5_1_2_1(), "rule__Pipeline__CancelConcurrenceAssignment_5_1_2_1");
			builder.put(grammarAccess.getPipelineAccess().getPipelineParametersAssignment_6(), "rule__Pipeline__PipelineParametersAssignment_6");
			builder.put(grammarAccess.getPipelineAccess().getVmNameAssignment_7_1_0_1_1(), "rule__Pipeline__VmNameAssignment_7_1_0_1_1");
			builder.put(grammarAccess.getPipelineAccess().getVmImageAssignment_7_1_0_2_1(), "rule__Pipeline__VmImageAssignment_7_1_0_2_1");
			builder.put(grammarAccess.getPipelineAccess().getVmDemandsAssignment_7_1_1_0_1(), "rule__Pipeline__VmDemandsAssignment_7_1_1_0_1");
			builder.put(grammarAccess.getPipelineAccess().getResourcesAssignment_8_1_1(), "rule__Pipeline__ResourcesAssignment_8_1_1");
			builder.put(grammarAccess.getPipelineAccess().getVersionAssignment_9_1(), "rule__Pipeline__VersionAssignment_9_1");
			builder.put(grammarAccess.getPipelineAccess().getPplVariablesAssignment_10_1(), "rule__Pipeline__PplVariablesAssignment_10_1");
			builder.put(grammarAccess.getPipelineAccess().getExtendedParameterAssignment_11(), "rule__Pipeline__ExtendedParameterAssignment_11");
			builder.put(grammarAccess.getPipelineAccess().getPipelineParametersAssignment_12_0(), "rule__Pipeline__PipelineParametersAssignment_12_0");
			builder.put(grammarAccess.getPipelineAccess().getJobOrStageVarAssignment_12_1_0(), "rule__Pipeline__JobOrStageVarAssignment_12_1_0");
			builder.put(grammarAccess.getPipelineAccess().getStagesAssignment_12_1_2_0(), "rule__Pipeline__StagesAssignment_12_1_2_0");
			builder.put(grammarAccess.getPipelineAccess().getJobsAssignment_12_1_2_1(), "rule__Pipeline__JobsAssignment_12_1_2_1");
			builder.put(grammarAccess.getExtendedParameterAccess().getTemplateAssignment_0_1_1_1(), "rule__ExtendedParameter__TemplateAssignment_0_1_1_1");
			builder.put(grammarAccess.getExtendedParameterAccess().getExtendedParameterValuesAssignment_0_1_2_1_1(), "rule__ExtendedParameter__ExtendedParameterValuesAssignment_0_1_2_1_1");
			builder.put(grammarAccess.getExtendedParameterAccess().getExtendedParameterValuesAssignment_1_1_1(), "rule__ExtendedParameter__ExtendedParameterValuesAssignment_1_1_1");
			builder.put(grammarAccess.getVariableAccess().getVariableValuesAssignment_0_1(), "rule__Variable__VariableValuesAssignment_0_1");
			builder.put(grammarAccess.getVariableAccess().getGroupAssignment_1_0_2(), "rule__Variable__GroupAssignment_1_0_2");
			builder.put(grammarAccess.getVariableAccess().getNameAssignment_1_1_0_2(), "rule__Variable__NameAssignment_1_1_0_2");
			builder.put(grammarAccess.getVariableAccess().getValueAssignment_1_1_1_1_1(), "rule__Variable__ValueAssignment_1_1_1_1_1");
			builder.put(grammarAccess.getVariableAccess().getReadonlyAssignment_1_1_1_2_1(), "rule__Variable__ReadonlyAssignment_1_1_1_2_1");
			builder.put(grammarAccess.getResourceAccess().getResourceNameAssignment_0(), "rule__Resource__ResourceNameAssignment_0");
			builder.put(grammarAccess.getResourceAccess().getResourceValuesAssignment_1_0_1(), "rule__Resource__ResourceValuesAssignment_1_0_1");
			builder.put(grammarAccess.getResourceAccess().getResourceValuesAssignment_1_1_1_1(), "rule__Resource__ResourceValuesAssignment_1_1_1_1");
			builder.put(grammarAccess.getPipelineParameterAccess().getNameAssignment_0_0(), "rule__PipelineParameter__NameAssignment_0_0");
			builder.put(grammarAccess.getPipelineParameterAccess().getParameterValuesAssignment_0_1(), "rule__PipelineParameter__ParameterValuesAssignment_0_1");
			builder.put(grammarAccess.getPipelineParameterAccess().getNameAssignment_1_0(), "rule__PipelineParameter__NameAssignment_1_0");
			builder.put(grammarAccess.getPipelineParameterAccess().getParameterValuesAssignment_1_1_1(), "rule__PipelineParameter__ParameterValuesAssignment_1_1_1");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_0_0_0(), "rule__Event__NameAssignment_0_0_0");
			builder.put(grammarAccess.getEventAccess().getIncludedBranchesAssignment_0_1(), "rule__Event__IncludedBranchesAssignment_0_1");
			builder.put(grammarAccess.getEventAccess().getActivitiesAssignment_0_2_1_0_1(), "rule__Event__ActivitiesAssignment_0_2_1_0_1");
			builder.put(grammarAccess.getEventAccess().getActivitiesAssignment_0_2_1_1_1(), "rule__Event__ActivitiesAssignment_0_2_1_1_1");
			builder.put(grammarAccess.getEventAccess().getBatchAssignment_0_2_2_0_1(), "rule__Event__BatchAssignment_0_2_2_0_1");
			builder.put(grammarAccess.getEventAccess().getAutoCancelAssignment_0_2_2_1_1(), "rule__Event__AutoCancelAssignment_0_2_2_1_1");
			builder.put(grammarAccess.getEventAccess().getDraftsAssignment_0_2_2_2_1(), "rule__Event__DraftsAssignment_0_2_2_2_1");
			builder.put(grammarAccess.getEventAccess().getIncludedBranchesAssignment_0_2_2_3_1_0_0(), "rule__Event__IncludedBranchesAssignment_0_2_2_3_1_0_0");
			builder.put(grammarAccess.getEventAccess().getIncludedBranchesAssignment_0_2_2_3_1_0_1_1(), "rule__Event__IncludedBranchesAssignment_0_2_2_3_1_0_1_1");
			builder.put(grammarAccess.getEventAccess().getIncludedBranchesAssignment_0_2_2_3_1_0_1_2_1(), "rule__Event__IncludedBranchesAssignment_0_2_2_3_1_0_1_2_1");
			builder.put(grammarAccess.getEventAccess().getIncludedBranchesAssignment_0_2_2_3_1_1_1(), "rule__Event__IncludedBranchesAssignment_0_2_2_3_1_1_1");
			builder.put(grammarAccess.getEventAccess().getIncludedBranchesAssignment_0_2_2_3_1_1_2_1(), "rule__Event__IncludedBranchesAssignment_0_2_2_3_1_1_2_1");
			builder.put(grammarAccess.getEventAccess().getExcludedBranchesAssignment_0_2_2_3_1_1_3_1(), "rule__Event__ExcludedBranchesAssignment_0_2_2_3_1_1_3_1");
			builder.put(grammarAccess.getEventAccess().getExcludedBranchesAssignment_0_2_2_4_1_0_0(), "rule__Event__ExcludedBranchesAssignment_0_2_2_4_1_0_0");
			builder.put(grammarAccess.getEventAccess().getExcludedBranchesAssignment_0_2_2_4_1_0_1_1(), "rule__Event__ExcludedBranchesAssignment_0_2_2_4_1_0_1_1");
			builder.put(grammarAccess.getEventAccess().getExcludedBranchesAssignment_0_2_2_4_1_0_1_2_1(), "rule__Event__ExcludedBranchesAssignment_0_2_2_4_1_0_1_2_1");
			builder.put(grammarAccess.getEventAccess().getExcludedBranchesAssignment_0_2_2_4_1_1_1(), "rule__Event__ExcludedBranchesAssignment_0_2_2_4_1_1_1");
			builder.put(grammarAccess.getEventAccess().getIncludedPathsAssignment_0_2_2_5_1(), "rule__Event__IncludedPathsAssignment_0_2_2_5_1");
			builder.put(grammarAccess.getEventAccess().getIncludedPathsAssignment_0_2_2_5_2_1(), "rule__Event__IncludedPathsAssignment_0_2_2_5_2_1");
			builder.put(grammarAccess.getEventAccess().getIncludedPathsAssignment_0_2_2_5_2_2_1(), "rule__Event__IncludedPathsAssignment_0_2_2_5_2_2_1");
			builder.put(grammarAccess.getEventAccess().getExcludedPathsAssignment_0_2_2_5_2_3_1(), "rule__Event__ExcludedPathsAssignment_0_2_2_5_2_3_1");
			builder.put(grammarAccess.getEventAccess().getExcludedPathsAssignment_0_2_2_6_1(), "rule__Event__ExcludedPathsAssignment_0_2_2_6_1");
			builder.put(grammarAccess.getEventAccess().getExcludedPathsAssignment_0_2_2_6_2_1(), "rule__Event__ExcludedPathsAssignment_0_2_2_6_2_1");
			builder.put(grammarAccess.getEventAccess().getIncludedTagsAssignment_0_2_2_7_1(), "rule__Event__IncludedTagsAssignment_0_2_2_7_1");
			builder.put(grammarAccess.getEventAccess().getIncludedTagsAssignment_0_2_2_7_2_1(), "rule__Event__IncludedTagsAssignment_0_2_2_7_2_1");
			builder.put(grammarAccess.getEventAccess().getIncludedTagsAssignment_0_2_2_7_2_2_1(), "rule__Event__IncludedTagsAssignment_0_2_2_7_2_2_1");
			builder.put(grammarAccess.getEventAccess().getExcludedTagsAssignment_0_2_2_7_2_3_1(), "rule__Event__ExcludedTagsAssignment_0_2_2_7_2_3_1");
			builder.put(grammarAccess.getEventAccess().getExcludedTagsAssignment_0_2_2_8_1(), "rule__Event__ExcludedTagsAssignment_0_2_2_8_1");
			builder.put(grammarAccess.getEventAccess().getExcludedTagsAssignment_0_2_2_8_2_1(), "rule__Event__ExcludedTagsAssignment_0_2_2_8_2_1");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_1_0_0(), "rule__Event__NameAssignment_1_0_0");
			builder.put(grammarAccess.getEventAccess().getTriggerSchedulesAssignment_1_0_1(), "rule__Event__TriggerSchedulesAssignment_1_0_1");
			builder.put(grammarAccess.getEventAccess().getNameAssignment_1_1_0(), "rule__Event__NameAssignment_1_1_0");
			builder.put(grammarAccess.getEventAccess().getOtherEventParameterValuesAssignment_1_1_1(), "rule__Event__OtherEventParameterValuesAssignment_1_1_1");
			builder.put(grammarAccess.getTriggerScheduleAccess().getCronValueAssignment_0_0_2(), "rule__TriggerSchedule__CronValueAssignment_0_0_2");
			builder.put(grammarAccess.getTriggerScheduleAccess().getCronValueAssignment_0_1_1_2(), "rule__TriggerSchedule__CronValueAssignment_0_1_1_2");
			builder.put(grammarAccess.getTriggerScheduleAccess().getDisplayNameAssignment_1_1_1(), "rule__TriggerSchedule__DisplayNameAssignment_1_1_1");
			builder.put(grammarAccess.getTriggerScheduleAccess().getIncludedBranchesAssignment_1_2_1_1_1(), "rule__TriggerSchedule__IncludedBranchesAssignment_1_2_1_1_1");
			builder.put(grammarAccess.getTriggerScheduleAccess().getExcludedBranchesAssignment_1_2_1_2_1(), "rule__TriggerSchedule__ExcludedBranchesAssignment_1_2_1_2_1");
			builder.put(grammarAccess.getTriggerScheduleAccess().getBatchAssignment_1_3_0_1(), "rule__TriggerSchedule__BatchAssignment_1_3_0_1");
			builder.put(grammarAccess.getTriggerScheduleAccess().getAlwaysAssignment_1_3_1_1(), "rule__TriggerSchedule__AlwaysAssignment_1_3_1_1");
			builder.put(grammarAccess.getBranchAccess().getNameAssignment_1(), "rule__Branch__NameAssignment_1");
			builder.put(grammarAccess.getActivityAccess().getNameAssignment(), "rule__Activity__NameAssignment");
			builder.put(grammarAccess.getStageAccess().getNameAssignment_0_2(), "rule__Stage__NameAssignment_0_2");
			builder.put(grammarAccess.getStageAccess().getDisplayNameAssignment_1_0_1_1(), "rule__Stage__DisplayNameAssignment_1_0_1_1");
			builder.put(grammarAccess.getStageAccess().getPoolValueAssignment_1_1_1_0(), "rule__Stage__PoolValueAssignment_1_1_1_0");
			builder.put(grammarAccess.getStageAccess().getVmNameAssignment_1_1_1_1_0_1_1(), "rule__Stage__VmNameAssignment_1_1_1_1_0_1_1");
			builder.put(grammarAccess.getStageAccess().getVmImageAssignment_1_1_1_1_0_2_1(), "rule__Stage__VmImageAssignment_1_1_1_1_0_2_1");
			builder.put(grammarAccess.getStageAccess().getVmDemandsAssignment_1_1_1_1_1_0_1(), "rule__Stage__VmDemandsAssignment_1_1_1_1_1_0_1");
			builder.put(grammarAccess.getStageAccess().getConditionValueAssignment_1_2_1(), "rule__Stage__ConditionValueAssignment_1_2_1");
			builder.put(grammarAccess.getStageAccess().getIsSkippableAssignment_1_3_1(), "rule__Stage__IsSkippableAssignment_1_3_1");
			builder.put(grammarAccess.getStageAccess().getStageVariablesAssignment_1_4_1(), "rule__Stage__StageVariablesAssignment_1_4_1");
			builder.put(grammarAccess.getStageAccess().getDependsOnAssignment_1_5_1(), "rule__Stage__DependsOnAssignment_1_5_1");
			builder.put(grammarAccess.getStageAccess().getJobsAssignment_1_6_0_1(), "rule__Stage__JobsAssignment_1_6_0_1");
			builder.put(grammarAccess.getJobAccess().getNameAssignment_0_1(), "rule__Job__NameAssignment_0_1");
			builder.put(grammarAccess.getJobAccess().getNameKWAssignment_1_0_1_0(), "rule__Job__NameKWAssignment_1_0_1_0");
			builder.put(grammarAccess.getJobAccess().getJobNameAssignment_1_0_1_1(), "rule__Job__JobNameAssignment_1_0_1_1");
			builder.put(grammarAccess.getJobAccess().getDependKWAssignment_1_1_0(), "rule__Job__DependKWAssignment_1_1_0");
			builder.put(grammarAccess.getJobAccess().getReferencesAssignment_1_1_1_0(), "rule__Job__ReferencesAssignment_1_1_1_0");
			builder.put(grammarAccess.getJobAccess().getReferencesAssignment_1_1_1_1_1(), "rule__Job__ReferencesAssignment_1_1_1_1_1");
			builder.put(grammarAccess.getJobAccess().getReferencesAssignment_1_1_1_1_2_1(), "rule__Job__ReferencesAssignment_1_1_1_1_2_1");
			builder.put(grammarAccess.getJobAccess().getJobParameterValuesAssignment_1_2_0(), "rule__Job__JobParameterValuesAssignment_1_2_0");
			builder.put(grammarAccess.getJobAccess().getStepsAssignment_1_2_1_1(), "rule__Job__StepsAssignment_1_2_1_1");
			builder.put(grammarAccess.getJobParameterAccess().getNameAssignment_0_0(), "rule__JobParameter__NameAssignment_0_0");
			builder.put(grammarAccess.getJobParameterAccess().getOtherNameAssignment_0_1_0(), "rule__JobParameter__OtherNameAssignment_0_1_0");
			builder.put(grammarAccess.getJobParameterAccess().getValueAssignment_1_0(), "rule__JobParameter__ValueAssignment_1_0");
			builder.put(grammarAccess.getJobParameterAccess().getSubParametersAssignment_1_1_1(), "rule__JobParameter__SubParametersAssignment_1_1_1");
			builder.put(grammarAccess.getScriptAccess().getNameAssignment_0_0(), "rule__Script__NameAssignment_0_0");
			builder.put(grammarAccess.getScriptAccess().getCommandAssignment_0_1_0(), "rule__Script__CommandAssignment_0_1_0");
			builder.put(grammarAccess.getScriptAccess().getCommandAssignment_0_1_1_2(), "rule__Script__CommandAssignment_0_1_1_2");
			builder.put(grammarAccess.getScriptAccess().getSubStepsAssignment_1_1(), "rule__Script__SubStepsAssignment_1_1");
			builder.put(grammarAccess.getActionAccess().getStepNameAssignment_0_0_1(), "rule__Action__StepNameAssignment_0_0_1");
			builder.put(grammarAccess.getActionAccess().getActionKeywordAssignment_0_1_0_0(), "rule__Action__ActionKeywordAssignment_0_1_0_0");
			builder.put(grammarAccess.getActionAccess().getOtherKeywordAssignment_0_1_0_1_0(), "rule__Action__OtherKeywordAssignment_0_1_0_1_0");
			builder.put(grammarAccess.getActionAccess().getActionValueAssignment_0_1_1(), "rule__Action__ActionValueAssignment_0_1_1");
			builder.put(grammarAccess.getActionAccess().getSubStepsAssignment_1_1(), "rule__Action__SubStepsAssignment_1_1");
			builder.put(grammarAccess.getParameterValueAccess().getNameAssignment_1(), "rule__ParameterValue__NameAssignment_1");
			builder.put(grammarAccess.getParameterValueAccess().getSubParameterValuesAssignment_4_0_1(), "rule__ParameterValue__SubParameterValuesAssignment_4_0_1");
			builder.put(grammarAccess.getParameterValueAccess().getValueAssignment_4_1_0(), "rule__ParameterValue__ValueAssignment_4_1_0");
			builder.put(grammarAccess.getParameterValueAccess().getSubParameterValuesAssignment_4_1_1_1(), "rule__ParameterValue__SubParameterValuesAssignment_4_1_1_1");
			builder.put(grammarAccess.getPipelineAccess().getUnorderedGroup(), "rule__Pipeline__UnorderedGroup");
			builder.put(grammarAccess.getPipelineAccess().getUnorderedGroup_2(), "rule__Pipeline__UnorderedGroup_2");
			builder.put(grammarAccess.getPipelineAccess().getUnorderedGroup_7_1(), "rule__Pipeline__UnorderedGroup_7_1");
			builder.put(grammarAccess.getEventAccess().getUnorderedGroup_0_2_2(), "rule__Event__UnorderedGroup_0_2_2");
			builder.put(grammarAccess.getTriggerScheduleAccess().getUnorderedGroup_1_3(), "rule__TriggerSchedule__UnorderedGroup_1_3");
			builder.put(grammarAccess.getStageAccess().getUnorderedGroup_1(), "rule__Stage__UnorderedGroup_1");
			builder.put(grammarAccess.getStageAccess().getUnorderedGroup_1_1_1_1(), "rule__Stage__UnorderedGroup_1_1_1_1");
			builder.put(grammarAccess.getJobAccess().getUnorderedGroup_1(), "rule__Job__UnorderedGroup_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PipelineGrammarAccess grammarAccess;

	@Override
	protected InternalPipelineParser createParser() {
		InternalPipelineParser result = new InternalPipelineParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new PipelineTokenSource(super.createLexer(stream));
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PipelineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PipelineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
