/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Configurations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getRunName <em>Run Name</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getDefaultShellValue <em>Default Shell Value</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getDefaultWDValue <em>Default WD Value</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getEnv <em>Env</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getAllPermission <em>All Permission</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getIndPermissions <em>Ind Permissions</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getGroup <em>Group</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getCancelConcurrence <em>Cancel Concurrence</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVmName <em>Vm Name</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVmImage <em>Vm Image</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVmDemands <em>Vm Demands</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getResources <em>Resources</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVersion <em>Version</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getPplVariables <em>Ppl Variables</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getParas <em>Paras</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getExtendOrInclude <em>Extend Or Include</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getExtendedParameters <em>Extended Parameters</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations()
 * @model
 * @generated
 */
public interface Configurations extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Run Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Run Name</em>' attribute.
   * @see #setRunName(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_RunName()
   * @model
   * @generated
   */
  String getRunName();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getRunName <em>Run Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Run Name</em>' attribute.
   * @see #getRunName()
   * @generated
   */
  void setRunName(String value);

  /**
   * Returns the value of the '<em><b>Default Shell Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Shell Value</em>' attribute.
   * @see #setDefaultShellValue(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_DefaultShellValue()
   * @model
   * @generated
   */
  String getDefaultShellValue();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getDefaultShellValue <em>Default Shell Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Shell Value</em>' attribute.
   * @see #getDefaultShellValue()
   * @generated
   */
  void setDefaultShellValue(String value);

  /**
   * Returns the value of the '<em><b>Default WD Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default WD Value</em>' attribute.
   * @see #setDefaultWDValue(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_DefaultWDValue()
   * @model
   * @generated
   */
  String getDefaultWDValue();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getDefaultWDValue <em>Default WD Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default WD Value</em>' attribute.
   * @see #getDefaultWDValue()
   * @generated
   */
  void setDefaultWDValue(String value);

  /**
   * Returns the value of the '<em><b>Env</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env</em>' attribute list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_Env()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnv();

  /**
   * Returns the value of the '<em><b>All Permission</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>All Permission</em>' attribute.
   * @see #setAllPermission(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_AllPermission()
   * @model
   * @generated
   */
  String getAllPermission();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getAllPermission <em>All Permission</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>All Permission</em>' attribute.
   * @see #getAllPermission()
   * @generated
   */
  void setAllPermission(String value);

  /**
   * Returns the value of the '<em><b>Ind Permissions</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ind Permissions</em>' attribute list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_IndPermissions()
   * @model unique="false"
   * @generated
   */
  EList<String> getIndPermissions();

  /**
   * Returns the value of the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Group</em>' attribute.
   * @see #setGroup(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_Group()
   * @model
   * @generated
   */
  String getGroup();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getGroup <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Group</em>' attribute.
   * @see #getGroup()
   * @generated
   */
  void setGroup(String value);

  /**
   * Returns the value of the '<em><b>Cancel Concurrence</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cancel Concurrence</em>' attribute.
   * @see #setCancelConcurrence(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_CancelConcurrence()
   * @model
   * @generated
   */
  String getCancelConcurrence();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getCancelConcurrence <em>Cancel Concurrence</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cancel Concurrence</em>' attribute.
   * @see #getCancelConcurrence()
   * @generated
   */
  void setCancelConcurrence(String value);

  /**
   * Returns the value of the '<em><b>Vm Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vm Name</em>' attribute.
   * @see #setVmName(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_VmName()
   * @model
   * @generated
   */
  String getVmName();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVmName <em>Vm Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vm Name</em>' attribute.
   * @see #getVmName()
   * @generated
   */
  void setVmName(String value);

  /**
   * Returns the value of the '<em><b>Vm Image</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vm Image</em>' attribute.
   * @see #setVmImage(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_VmImage()
   * @model
   * @generated
   */
  String getVmImage();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVmImage <em>Vm Image</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vm Image</em>' attribute.
   * @see #getVmImage()
   * @generated
   */
  void setVmImage(String value);

  /**
   * Returns the value of the '<em><b>Vm Demands</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vm Demands</em>' attribute.
   * @see #setVmDemands(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_VmDemands()
   * @model
   * @generated
   */
  String getVmDemands();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVmDemands <em>Vm Demands</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vm Demands</em>' attribute.
   * @see #getVmDemands()
   * @generated
   */
  void setVmDemands(String value);

  /**
   * Returns the value of the '<em><b>Resources</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.Resource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resources</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_Resources()
   * @model containment="true"
   * @generated
   */
  EList<Resource> getResources();

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Ppl Variables</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.Variable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ppl Variables</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_PplVariables()
   * @model containment="true"
   * @generated
   */
  EList<Variable> getPplVariables();

  /**
   * Returns the value of the '<em><b>Paras</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.ParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paras</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_Paras()
   * @model containment="true"
   * @generated
   */
  EList<ParameterValue> getParas();

  /**
   * Returns the value of the '<em><b>Extend Or Include</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extend Or Include</em>' attribute.
   * @see #setExtendOrInclude(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_ExtendOrInclude()
   * @model
   * @generated
   */
  String getExtendOrInclude();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Configurations#getExtendOrInclude <em>Extend Or Include</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extend Or Include</em>' attribute.
   * @see #getExtendOrInclude()
   * @generated
   */
  void setExtendOrInclude(String value);

  /**
   * Returns the value of the '<em><b>Extended Parameters</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.ParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extended Parameters</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getConfigurations_ExtendedParameters()
   * @model containment="true"
   * @generated
   */
  EList<ParameterValue> getExtendedParameters();

} // Configurations
