/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getSimpleEvent <em>Simple Event</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getIncludedBranches <em>Included Branches</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getActivities <em>Activities</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getBatch <em>Batch</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getAutoCancel <em>Auto Cancel</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getWorkflows <em>Workflows</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getDrafts <em>Drafts</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getExcludedBranches <em>Excluded Branches</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getIncludedPaths <em>Included Paths</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getExcludedPaths <em>Excluded Paths</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getIncludedTags <em>Included Tags</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getExcludedTags <em>Excluded Tags</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getScheduleNameKW <em>Schedule Name KW</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getTriggerSchedules <em>Trigger Schedules</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getWorkflowTypeKW <em>Workflow Type KW</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.Event#getWorkFlowActivities <em>Work Flow Activities</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.devops.pipeline.pipeline.PipelineEventKeyword}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelineEventKeyword
   * @see #setName(PipelineEventKeyword)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_Name()
   * @model
   * @generated
   */
  PipelineEventKeyword getName();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelineEventKeyword
   * @see #getName()
   * @generated
   */
  void setName(PipelineEventKeyword value);

  /**
   * Returns the value of the '<em><b>Simple Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Event</em>' attribute.
   * @see #setSimpleEvent(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_SimpleEvent()
   * @model
   * @generated
   */
  String getSimpleEvent();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getSimpleEvent <em>Simple Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple Event</em>' attribute.
   * @see #getSimpleEvent()
   * @generated
   */
  void setSimpleEvent(String value);

  /**
   * Returns the value of the '<em><b>Included Branches</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.Branch}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Included Branches</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_IncludedBranches()
   * @model containment="true"
   * @generated
   */
  EList<Branch> getIncludedBranches();

  /**
   * Returns the value of the '<em><b>Activities</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.Activity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Activities</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_Activities()
   * @model containment="true"
   * @generated
   */
  EList<Activity> getActivities();

  /**
   * Returns the value of the '<em><b>Batch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Batch</em>' attribute.
   * @see #setBatch(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_Batch()
   * @model
   * @generated
   */
  String getBatch();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getBatch <em>Batch</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Batch</em>' attribute.
   * @see #getBatch()
   * @generated
   */
  void setBatch(String value);

  /**
   * Returns the value of the '<em><b>Auto Cancel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Auto Cancel</em>' attribute.
   * @see #setAutoCancel(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_AutoCancel()
   * @model
   * @generated
   */
  String getAutoCancel();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getAutoCancel <em>Auto Cancel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Auto Cancel</em>' attribute.
   * @see #getAutoCancel()
   * @generated
   */
  void setAutoCancel(String value);

  /**
   * Returns the value of the '<em><b>Workflows</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflows</em>' attribute.
   * @see #setWorkflows(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_Workflows()
   * @model
   * @generated
   */
  String getWorkflows();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getWorkflows <em>Workflows</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Workflows</em>' attribute.
   * @see #getWorkflows()
   * @generated
   */
  void setWorkflows(String value);

  /**
   * Returns the value of the '<em><b>Drafts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Drafts</em>' attribute.
   * @see #setDrafts(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_Drafts()
   * @model
   * @generated
   */
  String getDrafts();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getDrafts <em>Drafts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Drafts</em>' attribute.
   * @see #getDrafts()
   * @generated
   */
  void setDrafts(String value);

  /**
   * Returns the value of the '<em><b>Excluded Branches</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.Branch}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Excluded Branches</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_ExcludedBranches()
   * @model containment="true"
   * @generated
   */
  EList<Branch> getExcludedBranches();

  /**
   * Returns the value of the '<em><b>Included Paths</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Included Paths</em>' attribute.
   * @see #setIncludedPaths(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_IncludedPaths()
   * @model
   * @generated
   */
  String getIncludedPaths();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getIncludedPaths <em>Included Paths</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Included Paths</em>' attribute.
   * @see #getIncludedPaths()
   * @generated
   */
  void setIncludedPaths(String value);

  /**
   * Returns the value of the '<em><b>Excluded Paths</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Excluded Paths</em>' attribute.
   * @see #setExcludedPaths(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_ExcludedPaths()
   * @model
   * @generated
   */
  String getExcludedPaths();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getExcludedPaths <em>Excluded Paths</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Excluded Paths</em>' attribute.
   * @see #getExcludedPaths()
   * @generated
   */
  void setExcludedPaths(String value);

  /**
   * Returns the value of the '<em><b>Included Tags</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Included Tags</em>' attribute.
   * @see #setIncludedTags(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_IncludedTags()
   * @model
   * @generated
   */
  String getIncludedTags();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getIncludedTags <em>Included Tags</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Included Tags</em>' attribute.
   * @see #getIncludedTags()
   * @generated
   */
  void setIncludedTags(String value);

  /**
   * Returns the value of the '<em><b>Excluded Tags</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Excluded Tags</em>' attribute.
   * @see #setExcludedTags(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_ExcludedTags()
   * @model
   * @generated
   */
  String getExcludedTags();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getExcludedTags <em>Excluded Tags</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Excluded Tags</em>' attribute.
   * @see #getExcludedTags()
   * @generated
   */
  void setExcludedTags(String value);

  /**
   * Returns the value of the '<em><b>Schedule Name KW</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schedule Name KW</em>' attribute.
   * @see #setScheduleNameKW(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_ScheduleNameKW()
   * @model
   * @generated
   */
  String getScheduleNameKW();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getScheduleNameKW <em>Schedule Name KW</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schedule Name KW</em>' attribute.
   * @see #getScheduleNameKW()
   * @generated
   */
  void setScheduleNameKW(String value);

  /**
   * Returns the value of the '<em><b>Trigger Schedules</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.TriggerSchedule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger Schedules</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_TriggerSchedules()
   * @model containment="true"
   * @generated
   */
  EList<TriggerSchedule> getTriggerSchedules();

  /**
   * Returns the value of the '<em><b>Workflow Type KW</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflow Type KW</em>' attribute.
   * @see #setWorkflowTypeKW(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_WorkflowTypeKW()
   * @model
   * @generated
   */
  String getWorkflowTypeKW();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.Event#getWorkflowTypeKW <em>Workflow Type KW</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Workflow Type KW</em>' attribute.
   * @see #getWorkflowTypeKW()
   * @generated
   */
  void setWorkflowTypeKW(String value);

  /**
   * Returns the value of the '<em><b>Work Flow Activities</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.Activity}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Work Flow Activities</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getEvent_WorkFlowActivities()
   * @model containment="true"
   * @generated
   */
  EList<Activity> getWorkFlowActivities();

} // Event
