/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Job Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.JobParameter#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.JobParameter#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.JobParameter#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getJobParameter()
 * @model
 * @generated
 */
public interface JobParameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getJobParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.JobParameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Keyword</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.devops.pipeline.pipeline.PipelineKeyword}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' attribute.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelineKeyword
   * @see #setKeyword(PipelineKeyword)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getJobParameter_Keyword()
   * @model
   * @generated
   */
  PipelineKeyword getKeyword();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.JobParameter#getKeyword <em>Keyword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' attribute.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelineKeyword
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(PipelineKeyword value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.ParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getJobParameter_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<ParameterValue> getParameters();

} // JobParameter
