/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getName <em>Name</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getPreDefinedKeyword <em>Pre Defined Keyword</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getSubParameterValues <em>Sub Parameter Values</em>}</li>
 *   <li>{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getParameterValue()
 * @model
 * @generated
 */
public interface ParameterValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getParameterValue_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Pre Defined Keyword</b></em>' attribute.
   * The literals are from the enumeration {@link ca.mcgill.devops.pipeline.pipeline.Permission}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Defined Keyword</em>' attribute.
   * @see ca.mcgill.devops.pipeline.pipeline.Permission
   * @see #setPreDefinedKeyword(Permission)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getParameterValue_PreDefinedKeyword()
   * @model
   * @generated
   */
  Permission getPreDefinedKeyword();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getPreDefinedKeyword <em>Pre Defined Keyword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre Defined Keyword</em>' attribute.
   * @see ca.mcgill.devops.pipeline.pipeline.Permission
   * @see #getPreDefinedKeyword()
   * @generated
   */
  void setPreDefinedKeyword(Permission value);

  /**
   * Returns the value of the '<em><b>Sub Parameter Values</b></em>' containment reference list.
   * The list contents are of type {@link ca.mcgill.devops.pipeline.pipeline.ParameterValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Parameter Values</em>' containment reference list.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getParameterValue_SubParameterValues()
   * @model containment="true"
   * @generated
   */
  EList<ParameterValue> getSubParameterValues();

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getParameterValue_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link ca.mcgill.devops.pipeline.pipeline.ParameterValue#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // ParameterValue
