/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Permission</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getPermission()
 * @model
 * @generated
 */
public enum Permission implements Enumerator
{
  /**
   * The '<em><b>READ ALL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #READ_ALL_VALUE
   * @generated
   * @ordered
   */
  READ_ALL(0, "READ_ALL", "read-all:"),

  /**
   * The '<em><b>WRITE ALL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WRITE_ALL_VALUE
   * @generated
   * @ordered
   */
  WRITE_ALL(1, "WRITE_ALL", "write-all:"),

  /**
   * The '<em><b>READ</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #READ_VALUE
   * @generated
   * @ordered
   */
  READ(2, "READ", "read:"),

  /**
   * The '<em><b>WRITE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WRITE_VALUE
   * @generated
   * @ordered
   */
  WRITE(3, "WRITE", "write:"),

  /**
   * The '<em><b>NONE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NONE_VALUE
   * @generated
   * @ordered
   */
  NONE(4, "NONE", "none:");

  /**
   * The '<em><b>READ ALL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #READ_ALL
   * @model literal="read-all:"
   * @generated
   * @ordered
   */
  public static final int READ_ALL_VALUE = 0;

  /**
   * The '<em><b>WRITE ALL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WRITE_ALL
   * @model literal="write-all:"
   * @generated
   * @ordered
   */
  public static final int WRITE_ALL_VALUE = 1;

  /**
   * The '<em><b>READ</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #READ
   * @model literal="read:"
   * @generated
   * @ordered
   */
  public static final int READ_VALUE = 2;

  /**
   * The '<em><b>WRITE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WRITE
   * @model literal="write:"
   * @generated
   * @ordered
   */
  public static final int WRITE_VALUE = 3;

  /**
   * The '<em><b>NONE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NONE
   * @model literal="none:"
   * @generated
   * @ordered
   */
  public static final int NONE_VALUE = 4;

  /**
   * An array of all the '<em><b>Permission</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Permission[] VALUES_ARRAY =
    new Permission[]
    {
      READ_ALL,
      WRITE_ALL,
      READ,
      WRITE,
      NONE,
    };

  /**
   * A public read-only list of all the '<em><b>Permission</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Permission> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Permission</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Permission get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Permission result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Permission</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Permission getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Permission result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Permission</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Permission get(int value)
  {
    switch (value)
    {
      case READ_ALL_VALUE: return READ_ALL;
      case WRITE_ALL_VALUE: return WRITE_ALL;
      case READ_VALUE: return READ;
      case WRITE_VALUE: return WRITE;
      case NONE_VALUE: return NONE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Permission(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Permission
