/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see ca.mcgill.devops.pipeline.pipeline.PipelineFactory
 * @model kind="package"
 * @generated
 */
public interface PipelinePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "pipeline";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mcgill.ca/devops/pipeline/Pipeline";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "pipeline";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PipelinePackage eINSTANCE = ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl.init();

  /**
   * The meta object id for the '{@link ca.mcgill.devops.pipeline.pipeline.impl.PipelineImpl <em>Pipeline</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelineImpl
   * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getPipeline()
   * @generated
   */
  int PIPELINE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__NAME = 0;

  /**
   * The feature id for the '<em><b>Pipeline Configuration</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE__PIPELINE_CONFIGURATION = 1;

  /**
   * The number of structural features of the '<em>Pipeline</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIPELINE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link ca.mcgill.devops.pipeline.pipeline.impl.ConfigurationImpl <em>Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.devops.pipeline.pipeline.impl.ConfigurationImpl
   * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getConfiguration()
   * @generated
   */
  int CONFIGURATION = 1;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION__PARAMETERS = 0;

  /**
   * The number of structural features of the '<em>Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link ca.mcgill.devops.pipeline.pipeline.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.devops.pipeline.pipeline.impl.ParameterImpl
   * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PARAMETERS = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__VALUE = 2;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link ca.mcgill.devops.pipeline.pipeline.PipelineKeyword <em>Keyword</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.devops.pipeline.pipeline.PipelineKeyword
   * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getPipelineKeyword()
   * @generated
   */
  int PIPELINE_KEYWORD = 3;

  /**
   * The meta object id for the '{@link ca.mcgill.devops.pipeline.pipeline.Permission <em>Permission</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see ca.mcgill.devops.pipeline.pipeline.Permission
   * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getPermission()
   * @generated
   */
  int PERMISSION = 4;


  /**
   * Returns the meta object for class '{@link ca.mcgill.devops.pipeline.pipeline.Pipeline <em>Pipeline</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pipeline</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Pipeline
   * @generated
   */
  EClass getPipeline();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.devops.pipeline.pipeline.Pipeline#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Pipeline#getName()
   * @see #getPipeline()
   * @generated
   */
  EAttribute getPipeline_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.devops.pipeline.pipeline.Pipeline#getPipelineConfiguration <em>Pipeline Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pipeline Configuration</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Pipeline#getPipelineConfiguration()
   * @see #getPipeline()
   * @generated
   */
  EReference getPipeline_PipelineConfiguration();

  /**
   * Returns the meta object for class '{@link ca.mcgill.devops.pipeline.pipeline.Configuration <em>Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Configuration
   * @generated
   */
  EClass getConfiguration();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.devops.pipeline.pipeline.Configuration#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Configuration#getParameters()
   * @see #getConfiguration()
   * @generated
   */
  EReference getConfiguration_Parameters();

  /**
   * Returns the meta object for class '{@link ca.mcgill.devops.pipeline.pipeline.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.devops.pipeline.pipeline.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the containment reference list '{@link ca.mcgill.devops.pipeline.pipeline.Parameter#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Parameters</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Parameter#getParameters()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Parameters();

  /**
   * Returns the meta object for the attribute '{@link ca.mcgill.devops.pipeline.pipeline.Parameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Parameter#getValue()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Value();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.devops.pipeline.pipeline.PipelineKeyword <em>Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Keyword</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.PipelineKeyword
   * @generated
   */
  EEnum getPipelineKeyword();

  /**
   * Returns the meta object for enum '{@link ca.mcgill.devops.pipeline.pipeline.Permission <em>Permission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Permission</em>'.
   * @see ca.mcgill.devops.pipeline.pipeline.Permission
   * @generated
   */
  EEnum getPermission();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  PipelineFactory getPipelineFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link ca.mcgill.devops.pipeline.pipeline.impl.PipelineImpl <em>Pipeline</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelineImpl
     * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getPipeline()
     * @generated
     */
    EClass PIPELINE = eINSTANCE.getPipeline();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIPELINE__NAME = eINSTANCE.getPipeline_Name();

    /**
     * The meta object literal for the '<em><b>Pipeline Configuration</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PIPELINE__PIPELINE_CONFIGURATION = eINSTANCE.getPipeline_PipelineConfiguration();

    /**
     * The meta object literal for the '{@link ca.mcgill.devops.pipeline.pipeline.impl.ConfigurationImpl <em>Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.devops.pipeline.pipeline.impl.ConfigurationImpl
     * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getConfiguration()
     * @generated
     */
    EClass CONFIGURATION = eINSTANCE.getConfiguration();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION__PARAMETERS = eINSTANCE.getConfiguration_Parameters();

    /**
     * The meta object literal for the '{@link ca.mcgill.devops.pipeline.pipeline.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.devops.pipeline.pipeline.impl.ParameterImpl
     * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__PARAMETERS = eINSTANCE.getParameter_Parameters();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__VALUE = eINSTANCE.getParameter_Value();

    /**
     * The meta object literal for the '{@link ca.mcgill.devops.pipeline.pipeline.PipelineKeyword <em>Keyword</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.devops.pipeline.pipeline.PipelineKeyword
     * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getPipelineKeyword()
     * @generated
     */
    EEnum PIPELINE_KEYWORD = eINSTANCE.getPipelineKeyword();

    /**
     * The meta object literal for the '{@link ca.mcgill.devops.pipeline.pipeline.Permission <em>Permission</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see ca.mcgill.devops.pipeline.pipeline.Permission
     * @see ca.mcgill.devops.pipeline.pipeline.impl.PipelinePackageImpl#getPermission()
     * @generated
     */
    EEnum PERMISSION = eINSTANCE.getPermission();

  }

} //PipelinePackage
