/**
 * generated by Xtext 2.33.0
 */
package ca.mcgill.devops.pipeline.pipeline;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Event Keyword</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see ca.mcgill.devops.pipeline.pipeline.PipelinePackage#getPipelineEventKeyword()
 * @model
 * @generated
 */
public enum PipelineEventKeyword implements Enumerator
{
  /**
   * The '<em><b>PPL EVT PUSH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PUSH_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PUSH(0, "PPL_EVT_PUSH", "push:"),

  /**
   * The '<em><b>PPL EVT PULL REQUEST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PULL_REQUEST(1, "PPL_EVT_PULL_REQUEST", "pull_request:"),

  /**
   * The '<em><b>PPL EVT WORKFLOW DISPATCH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_DISPATCH_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_WORKFLOW_DISPATCH(2, "PPL_EVT_WORKFLOW_DISPATCH", "workflow_dispatch:"),

  /**
   * The '<em><b>PPL EVT REPOSITORY DISPATCH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REPOSITORY_DISPATCH_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_REPOSITORY_DISPATCH(3, "PPL_EVT_REPOSITORY_DISPATCH", "repository_dispatch:"),

  /**
   * The '<em><b>PPL EVT CHECK RUN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CHECK_RUN_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CHECK_RUN(4, "PPL_EVT_CHECK_RUN", "check_run:"),

  /**
   * The '<em><b>PPL EVT CHECK SUITE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CHECK_SUITE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CHECK_SUITE(5, "PPL_EVT_CHECK_SUITE", "check_suite:"),

  /**
   * The '<em><b>PPL EVT CREATE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CREATE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CREATE(6, "PPL_EVT_CREATE", "create:"),

  /**
   * The '<em><b>PPL EVT DELETE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DELETE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_DELETE(7, "PPL_EVT_DELETE", "delete:"),

  /**
   * The '<em><b>PPL EVT DEPLOYMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DEPLOYMENT_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_DEPLOYMENT(8, "PPL_EVT_DEPLOYMENT", "deployment:"),

  /**
   * The '<em><b>PPL EVT DEPLOYMENT STATUS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DEPLOYMENT_STATUS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_DEPLOYMENT_STATUS(9, "PPL_EVT_DEPLOYMENT_STATUS", "deployment_status:"),

  /**
   * The '<em><b>PPL EVT FORK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_FORK_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_FORK(10, "PPL_EVT_FORK", "fork:"),

  /**
   * The '<em><b>PPL EVT GOLLUM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_GOLLUM_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_GOLLUM(11, "PPL_EVT_GOLLUM", "gollum:"),

  /**
   * The '<em><b>PPL EVT ISSUE COMMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_ISSUE_COMMENT_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_ISSUE_COMMENT(12, "PPL_EVT_ISSUE_COMMENT", "issue_comment:"),

  /**
   * The '<em><b>PPL EVT ISSUES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_ISSUES_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_ISSUES(13, "PPL_EVT_ISSUES", "issues:"),

  /**
   * The '<em><b>PPL EVT LABEL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_LABEL_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_LABEL(14, "PPL_EVT_LABEL", "label:"),

  /**
   * The '<em><b>PPL EVT MILESTONE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_MILESTONE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_MILESTONE(15, "PPL_EVT_MILESTONE", "milestone:"),

  /**
   * The '<em><b>PPL EVT PAGE BUILD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PAGE_BUILD_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PAGE_BUILD(16, "PPL_EVT_PAGE_BUILD", "page_build:"),

  /**
   * The '<em><b>PPL EVT PROJECT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PROJECT_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PROJECT(17, "PPL_EVT_PROJECT", "project:"),

  /**
   * The '<em><b>PPL EVT PROJECT CARD</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PROJECT_CARD_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PROJECT_CARD(18, "PPL_EVT_PROJECT_CARD", "project_card:"),

  /**
   * The '<em><b>PPL EVT PROJECT COLUMN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PROJECT_COLUMN_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PROJECT_COLUMN(19, "PPL_EVT_PROJECT_COLUMN", "project_column:"),

  /**
   * The '<em><b>PPL EVT PUBLIC</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PUBLIC_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PUBLIC(20, "PPL_EVT_PUBLIC", "public:"),

  /**
   * The '<em><b>PPL EVT PULL REQUEST REVIEW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_REVIEW_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PULL_REQUEST_REVIEW(21, "PPL_EVT_PULL_REQUEST_REVIEW", "pull_request_review:"),

  /**
   * The '<em><b>PPL EVT PULL REQUEST REVIEW COMMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_REVIEW_COMMENT_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PULL_REQUEST_REVIEW_COMMENT(22, "PPL_EVT_PULL_REQUEST_REVIEW_COMMENT", "pull_request_review_comment:"),

  /**
   * The '<em><b>PPL EVT PULL REQUEST TARGET</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_TARGET_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PULL_REQUEST_TARGET(23, "PPL_EVT_PULL_REQUEST_TARGET", "pull_request_target:"),

  /**
   * The '<em><b>PPL EVT REGISTRY PACKAGE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REGISTRY_PACKAGE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_REGISTRY_PACKAGE(24, "PPL_EVT_REGISTRY_PACKAGE", "registry_package:"),

  /**
   * The '<em><b>PPL EVT RELEASE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_RELEASE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_RELEASE(25, "PPL_EVT_RELEASE", "release:"),

  /**
   * The '<em><b>PPL EVT STATUS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_STATUS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_STATUS(26, "PPL_EVT_STATUS", "status:"),

  /**
   * The '<em><b>PPL EVT WATCH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WATCH_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_WATCH(27, "PPL_EVT_WATCH", "watch:"),

  /**
   * The '<em><b>PPL EVT WORKFLOW CALL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_CALL_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_WORKFLOW_CALL(28, "PPL_EVT_WORKFLOW_CALL", "workflow_call:"),

  /**
   * The '<em><b>PPL EVT WORKFLOW RUN</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_RUN_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_WORKFLOW_RUN(29, "PPL_EVT_WORKFLOW_RUN", "workflow_run:"),

  /**
   * The '<em><b>PPL EVT TRIGGER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TRIGGER_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_TRIGGER(30, "PPL_EVT_TRIGGER", "trigger:"),

  /**
   * The '<em><b>PPL EVT PR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PR_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PR(31, "PPL_EVT_PR", "pr:"),

  /**
   * The '<em><b>PPL EVT BRANCHES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BRANCHES_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_BRANCHES(32, "PPL_EVT_BRANCHES", "branches:"),

  /**
   * The '<em><b>PPL EVT TAGS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TAGS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_TAGS(33, "PPL_EVT_TAGS", "tags:"),

  /**
   * The '<em><b>PPL EVT PATHS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PATHS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PATHS(34, "PPL_EVT_PATHS", "paths:"),

  /**
   * The '<em><b>PPL EVT AUTO CANCEL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_AUTO_CANCEL_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_AUTO_CANCEL(35, "PPL_EVT_AUTO_CANCEL", "autoCancel:"),

  /**
   * The '<em><b>PPL EVT DRAFTS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DRAFTS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_DRAFTS(36, "PPL_EVT_DRAFTS", "drafts:"),

  /**
   * The '<em><b>PPL EVT ONLY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_ONLY_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_ONLY(37, "PPL_EVT_ONLY", "only:"),

  /**
   * The '<em><b>PPL EVT EXCEPT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_EXCEPT_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_EXCEPT(38, "PPL_EVT_EXCEPT", "except:"),

  /**
   * The '<em><b>PPL EVT RULES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_RULES_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_RULES(39, "PPL_EVT_RULES", "rules:"),

  /**
   * The '<em><b>PPL EVT WORKFLOW RULES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_RULES_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_WORKFLOW_RULES(40, "PPL_EVT_WORKFLOW_RULES", "workflow.rules:"),

  /**
   * The '<em><b>PPL EVT PIPELINE SCHEDULE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PIPELINE_SCHEDULE_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PIPELINE_SCHEDULE(41, "PPL_EVT_PIPELINE_SCHEDULE", "pipeline_schedule:"),

  /**
   * The '<em><b>PPL EVT MERGE REQUESTS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_MERGE_REQUESTS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_MERGE_REQUESTS(42, "PPL_EVT_MERGE_REQUESTS", "merge_requests:"),

  /**
   * The '<em><b>PPL EVT CHANGES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CHANGES_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CHANGES(43, "PPL_EVT_CHANGES", "changes:"),

  /**
   * The '<em><b>PPL EVT PIPELINES</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PIPELINES_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PIPELINES(44, "PPL_EVT_PIPELINES", "pipelines:"),

  /**
   * The '<em><b>PPL EVT DEFAULT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DEFAULT_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_DEFAULT(45, "PPL_EVT_DEFAULT", "default:"),

  /**
   * The '<em><b>PPL EVT PULL REQUESTS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUESTS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PULL_REQUESTS(46, "PPL_EVT_PULL_REQUESTS", "pull-requests:"),

  /**
   * The '<em><b>PPL EVT CUSTOM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CUSTOM_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CUSTOM(47, "PPL_EVT_CUSTOM", "custom:"),

  /**
   * The '<em><b>PPL EVT CONDITIONS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CONDITIONS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CONDITIONS(48, "PPL_EVT_CONDITIONS", "conditions:"),

  /**
   * The '<em><b>PPL EVT BRANCH DELETED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BRANCH_DELETED_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_BRANCH_DELETED(49, "PPL_EVT_BRANCH_DELETED", "bitbucket-branch-deleted:"),

  /**
   * The '<em><b>PPL EVT BRANCH CREATED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BRANCH_CREATED_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_BRANCH_CREATED(50, "PPL_EVT_BRANCH_CREATED", "bitbucket-branch-created:"),

  /**
   * The '<em><b>PPL EVT TAG CREATED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TAG_CREATED_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_TAG_CREATED(51, "PPL_EVT_TAG_CREATED", "bitbucket-tag-created:"),

  /**
   * The '<em><b>PPL EVT TAG DELETED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TAG_DELETED_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_TAG_DELETED(52, "PPL_EVT_TAG_DELETED", "bitbucket-tag-deleted:"),

  /**
   * The '<em><b>PPL EVT REPOSITORY TRIGGER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REPOSITORY_TRIGGER_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_REPOSITORY_TRIGGER(53, "PPL_EVT_REPOSITORY_TRIGGER", "repository:"),

  /**
   * The '<em><b>PPL EVT SCHEDULED TRIGGER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_SCHEDULED_TRIGGER_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_SCHEDULED_TRIGGER(54, "PPL_EVT_SCHEDULED_TRIGGER", "scheduled:"),

  /**
   * The '<em><b>PPL EVT REMOTE TRIGGER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REMOTE_TRIGGER_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_REMOTE_TRIGGER(55, "PPL_EVT_REMOTE_TRIGGER", "remote:"),

  /**
   * The '<em><b>PPL EVT BITBUCKET TRIGGER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BITBUCKET_TRIGGER_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_BITBUCKET_TRIGGER(56, "PPL_EVT_BITBUCKET_TRIGGER", "bitbucket:"),

  /**
   * The '<em><b>PPL EVT PLAN BRANCH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PLAN_BRANCH_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_PLAN_BRANCH(57, "PPL_EVT_PLAN_BRANCH", "planBranch:"),

  /**
   * The '<em><b>PPL EVT CRON</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CRON_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_CRON(58, "PPL_EVT_CRON", "cron:"),

  /**
   * The '<em><b>PPL EVT NOTIFICATIONS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_NOTIFICATIONS_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_NOTIFICATIONS(59, "PPL_EVT_NOTIFICATIONS", "notifications:"),

  /**
   * The '<em><b>PPL EVT LOCK BEHAVIOR</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_LOCK_BEHAVIOR_VALUE
   * @generated
   * @ordered
   */
  PPL_EVT_LOCK_BEHAVIOR(60, "PPL_EVT_LOCK_BEHAVIOR", "lockBehavior:");

  /**
   * The '<em><b>PPL EVT PUSH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PUSH
   * @model literal="push:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PUSH_VALUE = 0;

  /**
   * The '<em><b>PPL EVT PULL REQUEST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST
   * @model literal="pull_request:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PULL_REQUEST_VALUE = 1;

  /**
   * The '<em><b>PPL EVT WORKFLOW DISPATCH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_DISPATCH
   * @model literal="workflow_dispatch:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_WORKFLOW_DISPATCH_VALUE = 2;

  /**
   * The '<em><b>PPL EVT REPOSITORY DISPATCH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REPOSITORY_DISPATCH
   * @model literal="repository_dispatch:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_REPOSITORY_DISPATCH_VALUE = 3;

  /**
   * The '<em><b>PPL EVT CHECK RUN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CHECK_RUN
   * @model literal="check_run:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CHECK_RUN_VALUE = 4;

  /**
   * The '<em><b>PPL EVT CHECK SUITE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CHECK_SUITE
   * @model literal="check_suite:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CHECK_SUITE_VALUE = 5;

  /**
   * The '<em><b>PPL EVT CREATE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CREATE
   * @model literal="create:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CREATE_VALUE = 6;

  /**
   * The '<em><b>PPL EVT DELETE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DELETE
   * @model literal="delete:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_DELETE_VALUE = 7;

  /**
   * The '<em><b>PPL EVT DEPLOYMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DEPLOYMENT
   * @model literal="deployment:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_DEPLOYMENT_VALUE = 8;

  /**
   * The '<em><b>PPL EVT DEPLOYMENT STATUS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DEPLOYMENT_STATUS
   * @model literal="deployment_status:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_DEPLOYMENT_STATUS_VALUE = 9;

  /**
   * The '<em><b>PPL EVT FORK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_FORK
   * @model literal="fork:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_FORK_VALUE = 10;

  /**
   * The '<em><b>PPL EVT GOLLUM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_GOLLUM
   * @model literal="gollum:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_GOLLUM_VALUE = 11;

  /**
   * The '<em><b>PPL EVT ISSUE COMMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_ISSUE_COMMENT
   * @model literal="issue_comment:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_ISSUE_COMMENT_VALUE = 12;

  /**
   * The '<em><b>PPL EVT ISSUES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_ISSUES
   * @model literal="issues:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_ISSUES_VALUE = 13;

  /**
   * The '<em><b>PPL EVT LABEL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_LABEL
   * @model literal="label:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_LABEL_VALUE = 14;

  /**
   * The '<em><b>PPL EVT MILESTONE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_MILESTONE
   * @model literal="milestone:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_MILESTONE_VALUE = 15;

  /**
   * The '<em><b>PPL EVT PAGE BUILD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PAGE_BUILD
   * @model literal="page_build:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PAGE_BUILD_VALUE = 16;

  /**
   * The '<em><b>PPL EVT PROJECT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PROJECT
   * @model literal="project:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PROJECT_VALUE = 17;

  /**
   * The '<em><b>PPL EVT PROJECT CARD</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PROJECT_CARD
   * @model literal="project_card:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PROJECT_CARD_VALUE = 18;

  /**
   * The '<em><b>PPL EVT PROJECT COLUMN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PROJECT_COLUMN
   * @model literal="project_column:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PROJECT_COLUMN_VALUE = 19;

  /**
   * The '<em><b>PPL EVT PUBLIC</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PUBLIC
   * @model literal="public:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PUBLIC_VALUE = 20;

  /**
   * The '<em><b>PPL EVT PULL REQUEST REVIEW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_REVIEW
   * @model literal="pull_request_review:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PULL_REQUEST_REVIEW_VALUE = 21;

  /**
   * The '<em><b>PPL EVT PULL REQUEST REVIEW COMMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_REVIEW_COMMENT
   * @model literal="pull_request_review_comment:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PULL_REQUEST_REVIEW_COMMENT_VALUE = 22;

  /**
   * The '<em><b>PPL EVT PULL REQUEST TARGET</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUEST_TARGET
   * @model literal="pull_request_target:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PULL_REQUEST_TARGET_VALUE = 23;

  /**
   * The '<em><b>PPL EVT REGISTRY PACKAGE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REGISTRY_PACKAGE
   * @model literal="registry_package:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_REGISTRY_PACKAGE_VALUE = 24;

  /**
   * The '<em><b>PPL EVT RELEASE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_RELEASE
   * @model literal="release:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_RELEASE_VALUE = 25;

  /**
   * The '<em><b>PPL EVT STATUS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_STATUS
   * @model literal="status:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_STATUS_VALUE = 26;

  /**
   * The '<em><b>PPL EVT WATCH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WATCH
   * @model literal="watch:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_WATCH_VALUE = 27;

  /**
   * The '<em><b>PPL EVT WORKFLOW CALL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_CALL
   * @model literal="workflow_call:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_WORKFLOW_CALL_VALUE = 28;

  /**
   * The '<em><b>PPL EVT WORKFLOW RUN</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_RUN
   * @model literal="workflow_run:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_WORKFLOW_RUN_VALUE = 29;

  /**
   * The '<em><b>PPL EVT TRIGGER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TRIGGER
   * @model literal="trigger:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_TRIGGER_VALUE = 30;

  /**
   * The '<em><b>PPL EVT PR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PR
   * @model literal="pr:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PR_VALUE = 31;

  /**
   * The '<em><b>PPL EVT BRANCHES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BRANCHES
   * @model literal="branches:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_BRANCHES_VALUE = 32;

  /**
   * The '<em><b>PPL EVT TAGS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TAGS
   * @model literal="tags:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_TAGS_VALUE = 33;

  /**
   * The '<em><b>PPL EVT PATHS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PATHS
   * @model literal="paths:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PATHS_VALUE = 34;

  /**
   * The '<em><b>PPL EVT AUTO CANCEL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_AUTO_CANCEL
   * @model literal="autoCancel:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_AUTO_CANCEL_VALUE = 35;

  /**
   * The '<em><b>PPL EVT DRAFTS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DRAFTS
   * @model literal="drafts:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_DRAFTS_VALUE = 36;

  /**
   * The '<em><b>PPL EVT ONLY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_ONLY
   * @model literal="only:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_ONLY_VALUE = 37;

  /**
   * The '<em><b>PPL EVT EXCEPT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_EXCEPT
   * @model literal="except:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_EXCEPT_VALUE = 38;

  /**
   * The '<em><b>PPL EVT RULES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_RULES
   * @model literal="rules:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_RULES_VALUE = 39;

  /**
   * The '<em><b>PPL EVT WORKFLOW RULES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_WORKFLOW_RULES
   * @model literal="workflow.rules:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_WORKFLOW_RULES_VALUE = 40;

  /**
   * The '<em><b>PPL EVT PIPELINE SCHEDULE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PIPELINE_SCHEDULE
   * @model literal="pipeline_schedule:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PIPELINE_SCHEDULE_VALUE = 41;

  /**
   * The '<em><b>PPL EVT MERGE REQUESTS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_MERGE_REQUESTS
   * @model literal="merge_requests:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_MERGE_REQUESTS_VALUE = 42;

  /**
   * The '<em><b>PPL EVT CHANGES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CHANGES
   * @model literal="changes:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CHANGES_VALUE = 43;

  /**
   * The '<em><b>PPL EVT PIPELINES</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PIPELINES
   * @model literal="pipelines:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PIPELINES_VALUE = 44;

  /**
   * The '<em><b>PPL EVT DEFAULT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_DEFAULT
   * @model literal="default:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_DEFAULT_VALUE = 45;

  /**
   * The '<em><b>PPL EVT PULL REQUESTS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PULL_REQUESTS
   * @model literal="pull-requests:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PULL_REQUESTS_VALUE = 46;

  /**
   * The '<em><b>PPL EVT CUSTOM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CUSTOM
   * @model literal="custom:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CUSTOM_VALUE = 47;

  /**
   * The '<em><b>PPL EVT CONDITIONS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CONDITIONS
   * @model literal="conditions:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CONDITIONS_VALUE = 48;

  /**
   * The '<em><b>PPL EVT BRANCH DELETED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BRANCH_DELETED
   * @model literal="bitbucket-branch-deleted:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_BRANCH_DELETED_VALUE = 49;

  /**
   * The '<em><b>PPL EVT BRANCH CREATED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BRANCH_CREATED
   * @model literal="bitbucket-branch-created:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_BRANCH_CREATED_VALUE = 50;

  /**
   * The '<em><b>PPL EVT TAG CREATED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TAG_CREATED
   * @model literal="bitbucket-tag-created:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_TAG_CREATED_VALUE = 51;

  /**
   * The '<em><b>PPL EVT TAG DELETED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_TAG_DELETED
   * @model literal="bitbucket-tag-deleted:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_TAG_DELETED_VALUE = 52;

  /**
   * The '<em><b>PPL EVT REPOSITORY TRIGGER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REPOSITORY_TRIGGER
   * @model literal="repository:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_REPOSITORY_TRIGGER_VALUE = 53;

  /**
   * The '<em><b>PPL EVT SCHEDULED TRIGGER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_SCHEDULED_TRIGGER
   * @model literal="scheduled:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_SCHEDULED_TRIGGER_VALUE = 54;

  /**
   * The '<em><b>PPL EVT REMOTE TRIGGER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_REMOTE_TRIGGER
   * @model literal="remote:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_REMOTE_TRIGGER_VALUE = 55;

  /**
   * The '<em><b>PPL EVT BITBUCKET TRIGGER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_BITBUCKET_TRIGGER
   * @model literal="bitbucket:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_BITBUCKET_TRIGGER_VALUE = 56;

  /**
   * The '<em><b>PPL EVT PLAN BRANCH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_PLAN_BRANCH
   * @model literal="planBranch:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_PLAN_BRANCH_VALUE = 57;

  /**
   * The '<em><b>PPL EVT CRON</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_CRON
   * @model literal="cron:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_CRON_VALUE = 58;

  /**
   * The '<em><b>PPL EVT NOTIFICATIONS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_NOTIFICATIONS
   * @model literal="notifications:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_NOTIFICATIONS_VALUE = 59;

  /**
   * The '<em><b>PPL EVT LOCK BEHAVIOR</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PPL_EVT_LOCK_BEHAVIOR
   * @model literal="lockBehavior:"
   * @generated
   * @ordered
   */
  public static final int PPL_EVT_LOCK_BEHAVIOR_VALUE = 60;

  /**
   * An array of all the '<em><b>Event Keyword</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final PipelineEventKeyword[] VALUES_ARRAY =
    new PipelineEventKeyword[]
    {
      PPL_EVT_PUSH,
      PPL_EVT_PULL_REQUEST,
      PPL_EVT_WORKFLOW_DISPATCH,
      PPL_EVT_REPOSITORY_DISPATCH,
      PPL_EVT_CHECK_RUN,
      PPL_EVT_CHECK_SUITE,
      PPL_EVT_CREATE,
      PPL_EVT_DELETE,
      PPL_EVT_DEPLOYMENT,
      PPL_EVT_DEPLOYMENT_STATUS,
      PPL_EVT_FORK,
      PPL_EVT_GOLLUM,
      PPL_EVT_ISSUE_COMMENT,
      PPL_EVT_ISSUES,
      PPL_EVT_LABEL,
      PPL_EVT_MILESTONE,
      PPL_EVT_PAGE_BUILD,
      PPL_EVT_PROJECT,
      PPL_EVT_PROJECT_CARD,
      PPL_EVT_PROJECT_COLUMN,
      PPL_EVT_PUBLIC,
      PPL_EVT_PULL_REQUEST_REVIEW,
      PPL_EVT_PULL_REQUEST_REVIEW_COMMENT,
      PPL_EVT_PULL_REQUEST_TARGET,
      PPL_EVT_REGISTRY_PACKAGE,
      PPL_EVT_RELEASE,
      PPL_EVT_STATUS,
      PPL_EVT_WATCH,
      PPL_EVT_WORKFLOW_CALL,
      PPL_EVT_WORKFLOW_RUN,
      PPL_EVT_TRIGGER,
      PPL_EVT_PR,
      PPL_EVT_BRANCHES,
      PPL_EVT_TAGS,
      PPL_EVT_PATHS,
      PPL_EVT_AUTO_CANCEL,
      PPL_EVT_DRAFTS,
      PPL_EVT_ONLY,
      PPL_EVT_EXCEPT,
      PPL_EVT_RULES,
      PPL_EVT_WORKFLOW_RULES,
      PPL_EVT_PIPELINE_SCHEDULE,
      PPL_EVT_MERGE_REQUESTS,
      PPL_EVT_CHANGES,
      PPL_EVT_PIPELINES,
      PPL_EVT_DEFAULT,
      PPL_EVT_PULL_REQUESTS,
      PPL_EVT_CUSTOM,
      PPL_EVT_CONDITIONS,
      PPL_EVT_BRANCH_DELETED,
      PPL_EVT_BRANCH_CREATED,
      PPL_EVT_TAG_CREATED,
      PPL_EVT_TAG_DELETED,
      PPL_EVT_REPOSITORY_TRIGGER,
      PPL_EVT_SCHEDULED_TRIGGER,
      PPL_EVT_REMOTE_TRIGGER,
      PPL_EVT_BITBUCKET_TRIGGER,
      PPL_EVT_PLAN_BRANCH,
      PPL_EVT_CRON,
      PPL_EVT_NOTIFICATIONS,
      PPL_EVT_LOCK_BEHAVIOR,
    };

  /**
   * A public read-only list of all the '<em><b>Event Keyword</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<PipelineEventKeyword> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Event Keyword</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PipelineEventKeyword get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PipelineEventKeyword result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Event Keyword</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PipelineEventKeyword getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      PipelineEventKeyword result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Event Keyword</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static PipelineEventKeyword get(int value)
  {
    switch (value)
    {
      case PPL_EVT_PUSH_VALUE: return PPL_EVT_PUSH;
      case PPL_EVT_PULL_REQUEST_VALUE: return PPL_EVT_PULL_REQUEST;
      case PPL_EVT_WORKFLOW_DISPATCH_VALUE: return PPL_EVT_WORKFLOW_DISPATCH;
      case PPL_EVT_REPOSITORY_DISPATCH_VALUE: return PPL_EVT_REPOSITORY_DISPATCH;
      case PPL_EVT_CHECK_RUN_VALUE: return PPL_EVT_CHECK_RUN;
      case PPL_EVT_CHECK_SUITE_VALUE: return PPL_EVT_CHECK_SUITE;
      case PPL_EVT_CREATE_VALUE: return PPL_EVT_CREATE;
      case PPL_EVT_DELETE_VALUE: return PPL_EVT_DELETE;
      case PPL_EVT_DEPLOYMENT_VALUE: return PPL_EVT_DEPLOYMENT;
      case PPL_EVT_DEPLOYMENT_STATUS_VALUE: return PPL_EVT_DEPLOYMENT_STATUS;
      case PPL_EVT_FORK_VALUE: return PPL_EVT_FORK;
      case PPL_EVT_GOLLUM_VALUE: return PPL_EVT_GOLLUM;
      case PPL_EVT_ISSUE_COMMENT_VALUE: return PPL_EVT_ISSUE_COMMENT;
      case PPL_EVT_ISSUES_VALUE: return PPL_EVT_ISSUES;
      case PPL_EVT_LABEL_VALUE: return PPL_EVT_LABEL;
      case PPL_EVT_MILESTONE_VALUE: return PPL_EVT_MILESTONE;
      case PPL_EVT_PAGE_BUILD_VALUE: return PPL_EVT_PAGE_BUILD;
      case PPL_EVT_PROJECT_VALUE: return PPL_EVT_PROJECT;
      case PPL_EVT_PROJECT_CARD_VALUE: return PPL_EVT_PROJECT_CARD;
      case PPL_EVT_PROJECT_COLUMN_VALUE: return PPL_EVT_PROJECT_COLUMN;
      case PPL_EVT_PUBLIC_VALUE: return PPL_EVT_PUBLIC;
      case PPL_EVT_PULL_REQUEST_REVIEW_VALUE: return PPL_EVT_PULL_REQUEST_REVIEW;
      case PPL_EVT_PULL_REQUEST_REVIEW_COMMENT_VALUE: return PPL_EVT_PULL_REQUEST_REVIEW_COMMENT;
      case PPL_EVT_PULL_REQUEST_TARGET_VALUE: return PPL_EVT_PULL_REQUEST_TARGET;
      case PPL_EVT_REGISTRY_PACKAGE_VALUE: return PPL_EVT_REGISTRY_PACKAGE;
      case PPL_EVT_RELEASE_VALUE: return PPL_EVT_RELEASE;
      case PPL_EVT_STATUS_VALUE: return PPL_EVT_STATUS;
      case PPL_EVT_WATCH_VALUE: return PPL_EVT_WATCH;
      case PPL_EVT_WORKFLOW_CALL_VALUE: return PPL_EVT_WORKFLOW_CALL;
      case PPL_EVT_WORKFLOW_RUN_VALUE: return PPL_EVT_WORKFLOW_RUN;
      case PPL_EVT_TRIGGER_VALUE: return PPL_EVT_TRIGGER;
      case PPL_EVT_PR_VALUE: return PPL_EVT_PR;
      case PPL_EVT_BRANCHES_VALUE: return PPL_EVT_BRANCHES;
      case PPL_EVT_TAGS_VALUE: return PPL_EVT_TAGS;
      case PPL_EVT_PATHS_VALUE: return PPL_EVT_PATHS;
      case PPL_EVT_AUTO_CANCEL_VALUE: return PPL_EVT_AUTO_CANCEL;
      case PPL_EVT_DRAFTS_VALUE: return PPL_EVT_DRAFTS;
      case PPL_EVT_ONLY_VALUE: return PPL_EVT_ONLY;
      case PPL_EVT_EXCEPT_VALUE: return PPL_EVT_EXCEPT;
      case PPL_EVT_RULES_VALUE: return PPL_EVT_RULES;
      case PPL_EVT_WORKFLOW_RULES_VALUE: return PPL_EVT_WORKFLOW_RULES;
      case PPL_EVT_PIPELINE_SCHEDULE_VALUE: return PPL_EVT_PIPELINE_SCHEDULE;
      case PPL_EVT_MERGE_REQUESTS_VALUE: return PPL_EVT_MERGE_REQUESTS;
      case PPL_EVT_CHANGES_VALUE: return PPL_EVT_CHANGES;
      case PPL_EVT_PIPELINES_VALUE: return PPL_EVT_PIPELINES;
      case PPL_EVT_DEFAULT_VALUE: return PPL_EVT_DEFAULT;
      case PPL_EVT_PULL_REQUESTS_VALUE: return PPL_EVT_PULL_REQUESTS;
      case PPL_EVT_CUSTOM_VALUE: return PPL_EVT_CUSTOM;
      case PPL_EVT_CONDITIONS_VALUE: return PPL_EVT_CONDITIONS;
      case PPL_EVT_BRANCH_DELETED_VALUE: return PPL_EVT_BRANCH_DELETED;
      case PPL_EVT_BRANCH_CREATED_VALUE: return PPL_EVT_BRANCH_CREATED;
      case PPL_EVT_TAG_CREATED_VALUE: return PPL_EVT_TAG_CREATED;
      case PPL_EVT_TAG_DELETED_VALUE: return PPL_EVT_TAG_DELETED;
      case PPL_EVT_REPOSITORY_TRIGGER_VALUE: return PPL_EVT_REPOSITORY_TRIGGER;
      case PPL_EVT_SCHEDULED_TRIGGER_VALUE: return PPL_EVT_SCHEDULED_TRIGGER;
      case PPL_EVT_REMOTE_TRIGGER_VALUE: return PPL_EVT_REMOTE_TRIGGER;
      case PPL_EVT_BITBUCKET_TRIGGER_VALUE: return PPL_EVT_BITBUCKET_TRIGGER;
      case PPL_EVT_PLAN_BRANCH_VALUE: return PPL_EVT_PLAN_BRANCH;
      case PPL_EVT_CRON_VALUE: return PPL_EVT_CRON;
      case PPL_EVT_NOTIFICATIONS_VALUE: return PPL_EVT_NOTIFICATIONS;
      case PPL_EVT_LOCK_BEHAVIOR_VALUE: return PPL_EVT_LOCK_BEHAVIOR;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private PipelineEventKeyword(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //PipelineEventKeyword
